# The likelihood against itself, through the data it generates.
#
# If the data really were drawn from the model at some parameter value, the
# gradient of the negative log likelihood at that same value is a mean-zero
# random vector. That is a property of any correct density and holds whether or
# not the value is the maximum, so it can be checked without fitting anything.
#
# What it catches is a likelihood that is not the density it simulates from: a
# missing Jacobian, a standard deviation applied on the wrong scale, a
# normalizing constant that depends on a parameter, a residual formed against the
# wrong prediction. None of those move the reported jnLL in a way a stored value
# would notice, and all of them bias the score away from zero.
#
# Two things constrain what can be checked this way.
#
# Only streams the objective registers with RTMB::OBS are regenerated, so only
# those may be fit here: a likelihood term whose data stay fixed across replicates
# contributes the same non-zero gradient every time and swamps the mean. That
# rules out the composition likelihoods, which are registered only on the OSA
# path, and it rules out the penalties and priors, which are not data at all.
#
# And the registered quantity is log(obs) subset to the cells the Use array flags,
# not the observation array itself, so a draw comes back log-scale and packed and
# has to be exponentiated and scattered back.

score_fixture <- function(n_yrs = 25, n_ages = 8) {
  off <- array(0, dim = c(1, n_yrs, 1, 1))
  sweep_input(
    dims = list(n_regions = 1, n_sexes = 1, n_fish_fleets = 1, n_srv_fleets = 1,
                n_yrs = n_yrs, n_ages = n_ages),
    # compositions are not regenerated by simulate(), so they are not fit
    fishidx = list(UseFishAgeComps = off, FishAgeComps_LikeType = "none"),
    srvidx = list(UseSrvAgeComps = off, SrvAgeComps_LikeType = "none"),
    wt = list(Wt_FishAgeComps = array(0, dim = c(1, n_yrs, 1, 1, 1)),
              Wt_FishLenComps = array(0, dim = c(1, n_yrs, 1, 1, 1)),
              Wt_SrvAgeComps = array(0, dim = c(1, n_yrs, 1, 1, 1)),
              Wt_SrvLenComps = array(0, dim = c(1, n_yrs, 1, 1, 1))))
}

SCORE_STREAMS <- c("ObsCatch", "ObsFishIdx", "ObsSrvIdx")

#' Put a simulated draw back into the data list
#'
#' @keywords internal
score_replace_obs <- function(data, sim) {
  for(nm in SCORE_STREAMS) {
    use <- data[[sub("^Obs", "Use", nm)]]
    data[[nm]][use == 1] <- exp(sim[[nm]])
  }
  data
}

#' Score at theta over replicate datasets generated at theta
#'
#' @param il Input list.
#' @param n_rep Replicates.
#' @param seed Seed, so a failure is reproducible.
#' @param obs_scale Multiplier applied to every simulated observation. One leaves
#'   the draw as the model made it; anything else describes data the model did not
#'   generate, which is how the check below is shown to have power.
#'
#' @return A list with the standardized mean score per parameter.
#'
#' @keywords internal
score_z <- function(il, n_rep = 120, seed = 2024, obs_scale = 1) {
  base <- fit_model(il$data, il$par, il$map, do_optim = FALSE, silent = TRUE)
  theta <- base$par

  set.seed(seed)
  G <- matrix(NA_real_, n_rep, length(theta))
  for(i in seq_len(n_rep)) {
    sim <- base$simulate()
    if(obs_scale != 1) for(nm in SCORE_STREAMS) sim[[nm]] <- sim[[nm]] + log(obs_scale)
    d <- score_replace_obs(il$data, sim)
    obj <- fit_model(d, il$par, il$map, do_optim = FALSE, silent = TRUE)
    G[i, ] <- as.numeric(obj$gr(theta))
  }

  m <- colMeans(G)
  se <- apply(G, 2, stats::sd) / sqrt(n_rep)
  list(z = ifelse(se > 0, m / se, 0), names = names(theta))
}


test_that("the score has mean zero on data the model generated", {
  # The likelihood is a proper density for the streams it simulates. With this
  # many parameters a handful of standardized means near two is ordinary; a
  # likelihood that disagreed with its own simulation would sit far outside.
  out <- score_z(score_fixture())

  worst <- which.max(abs(out$z))
  expect_lt(max(abs(out$z)), 4,
            label = sprintf("largest standardized mean score (%s = %.2f)",
                            out$names[worst], out$z[worst]))
})


test_that("the score check has the power to notice a mismatch", {
  # Shifting every simulated observation describes data the model did not
  # generate. If the check could not tell that apart from a correct draw it would
  # pass against any likelihood at all, and the test above would mean nothing.
  out <- score_z(score_fixture(), n_rep = 60, obs_scale = 1.25)

  expect_gt(max(abs(out$z)), 10)
})
