# Names R CMD check cannot see bindings for: objects read out of the RTMB::getAll frame, and dplyr/ggplot2
# column names. Regenerate from the 'Undefined global functions or variables' block of an R CMD check log.

utils::globalVariables(c(
  ".", "addtocomp", "addtofishidx", "addtosrvidx", "addtotag", "adjacency_collapsed",
  "fishsel_sex_apical_offset", "retsel_sex_apical_offset", "srvsel_sex_apical_offset",
  "adjacency_mat", "Age", "age_pool", "AgeingError", "AgeingError_fish", "AgeingError_srv", "ages", "area_r", "bias_year", "bin", "Bin",
  "catch_units", "cohort", "comp_const_obs", "cont_tv_fish_sel", "cont_tv_fishsel_bin_devs",
  "cont_tv_ret_sel", "cont_tv_retsel_bin_devs", "cont_tv_srv_sel", "cont_tv_srvsel_bin_devs",
  "cont_vary_movement", "conv_fish_tag_attr", "conv_fish_tag_like", "conv_tag_age_pool",
  "conv_tag_fish_reporting_blocks", "conv_tag_fish_reporting_pars", "conv_tag_fishrep_prior",
  "conv_tag_max_liberty", "conv_tag_mixing_period", "conv_tag_pop_pool",
  "conv_tag_release_indicator", "conv_tag_release_platform", "conv_tag_sex_pool",
  "conv_tag_t_tagging", "conv_tagged_fish", "ctmc_diffusion_bounds", "ctmc_diffusion_eps", "ctmc_move_dat",
  "ctmc_scale_by_seasdur", "diffusion_formula", "discard_units", "dmr", "do_fish_q_cov",
  "do_internal_comp_osa", "do_internal_conv_tag_osa", "do_rec_bias_ramp", "do_recruits_move",
  "do_srv_q_cov", "equil_init_age_strc", "est", "F_fract_flt", "Fdev_model", "Fdev_pen_center",
  "Fdev_rho", "fish_fixed_sel_pars", "fish_idx_ages", "fish_idx_type", "fish_q_blocks",
  "fish_q_coeff", "fish_q_cov", "fish_q_prior", "fish_q_type", "fish_sel",
  "fish_sel_bicubic_binnodes", "fish_sel_bicubic_nselbins", "fish_sel_bicubic_selstyr",
  "fish_sel_bicubic_Wbin", "fish_sel_bicubic_Wyr", "fish_sel_bicubic_yrnodes",
  "fish_sel_norm_bins", "ret_sel_norm_bins", "srv_sel_norm_bins",
  "sr_R0",
  "fish_sel_bin_dev_bins", "fish_sel_blocks", "fish_sel_input", "fish_sel_model",
  "fish_sel_pen_wts", "fish_selex_penalty", "fish_selex_prior", "fish_selex_type",
  "FishAge_corr_pars", "FishAge_corr_pars_agg", "FishAge_discard_corr_pars",
  "FishAge_discard_corr_pars_agg", "FishAge_discard_pop_corr_pars",
  "FishAge_discard_pop_corr_pars_agg", "FishAge_pop_corr_pars", "FishAge_pop_corr_pars_agg",
  "Fish_caal_bins", "FishAgeComps_bins", "FishAgeComps_discard_bins",
  "FishAgeComps_discard_LikeType", "FishAgeComps_discard_pop_bins",
  "FishAgeComps_discard_pop_LikeType",
  "FishAgeComps_discard_pop_Type", "FishAgeComps_discard_Type", "FishAgeComps_LikeType",
  "FishAgeComps_pop_bins", "FishAgeComps_pop_LikeType", "FishAgeComps_pop_Type",
  "FishAgeComps_Type", "FishLenComps_bins", "FishLenComps_discard_bins",
  "FishLenComps_discard_pop_bins", "FishLenComps_pop_bins", "FishIdx_Cov",
  "FishIdx_LikeType", "FishLen_corr_pars", "FishLen_corr_pars_agg", "FishLen_discard_corr_pars",
  "FishLen_discard_corr_pars_agg", "FishLen_discard_pop_corr_pars",
  "FishLen_discard_pop_corr_pars_agg", "FishLen_pop_corr_pars", "FishLen_pop_corr_pars_agg",
  "FishLenComps_discard_LikeType", "FishLenComps_discard_pop_LikeType",
  "FishLenComps_discard_pop_Type", "FishLenComps_discard_Type", "FishLenComps_LikeType",
  "FishLenComps_pop_LikeType", "FishLenComps_pop_Type", "FishLenComps_Type",
  "fishsel_bin_devs_pe_pars", "fishsel_bin_devs_rw_init_sigma", "fishsel_devs_min_shared_bins",
  "fishsel_pe_pars", "fishsel_pe_wt", "fishsel_rw_init_sigma", "fit_lengths", "Fixed_Movement",
  "Fixed_natmort", "fixed_rec_seas_prop", "fixed_stray_rate", "fleet", "Fleet", "from", "h",
  "h_prior", "HCI", "index", "init_age_devs_shared", "init_age_strc", "init_F_form", "init_F_par",
  "InitDevs_pen_center", "is_discard_fleet", "is_tail", "ISS_FishAgeComps",
  "ISS_FishAgeComps_discard", "ISS_FishAgeComps_discard_pop", "ISS_FishAgeComps_pop",
  "ISS_FishLenComps", "ISS_FishLenComps_discard", "ISS_FishLenComps_discard_pop",
  "ISS_FishLenComps_pop", "ISS_SrvAgeComps", "ISS_SrvAgeComps_pop", "ISS_SrvLenComps",
  "ISS_SrvLenComps_pop", "L1", "lci", "LCI", "lens", "ln_conv_fish_tag_theta", "ln_conv_tag_shed",
  "ln_F_devs", "ln_F_mean", "ln_fish_q", "ln_FishAge_discard_pop_theta",
  "ln_FishAge_discard_pop_theta_agg", "ln_FishAge_discard_theta", "ln_FishAge_discard_theta_agg",
  "ln_FishAge_pop_theta", "ln_FishAge_pop_theta_agg", "ln_FishAge_theta", "ln_FishAge_theta_agg",
  "ln_FishLen_discard_pop_theta", "ln_FishLen_discard_pop_theta_agg", "ln_FishLen_discard_theta",
  "ln_FishLen_discard_theta_agg", "ln_FishLen_pop_theta", "ln_FishLen_pop_theta_agg",
  "ln_FishLen_theta", "ln_FishLen_theta_agg", "ln_fishsel_bin_devs", "ln_fishsel_devs",
  "ln_fishsel_sex_scale", "fishsel_sex_par_offset", "fishsel_sex_scale_offset",
  "ln_srvsel_sex_scale", "srvsel_sex_par_offset", "srvsel_sex_scale_offset", "init_devs_pen_use",
  "ln_retsel_sex_scale", "retsel_sex_par_offset", "retsel_sex_scale_offset",
  "Use_init_sex_pen", "ln_sigma_init_sex",
  "ln_global_R0", "ln_init_conv_tag_mort", "ln_InitDevs", "ln_M", "ln_RecDevs",
  "ln_retsel_bin_devs", "ln_retsel_devs", "ln_rinit", "ln_sigma_dmr", "ln_sigma_rec_level",
  "ln_sigmaC", "ln_sigmaC_pop", "ln_sigmaCAA", "ln_sigmaD", "ln_sigmaD_pop", "ln_sigmaF", "ln_sigmaFishIdx",
  "ln_sigmaFishIdx_pop", "ln_sigmaR", "ln_sigmaSrvIdx", "ln_sigmaSrvIdx_pop", "ln_srv_q",
  "ObsCatchAA", "UseCatchAA", "use_catch_aa", "ObsCatchAA_pop", "UseCatchAA_pop",
  "ln_sigmaCAA_pop", "ObsSrvIdxAA", "UseSrvIdxAA", "ObsSrvIdxAA_pop", "UseSrvIdxAA_pop",
  "use_srv_idx_aa", "ln_sigmaSrvIdxAA", "ln_sigmaSrvIdxAA_pop",
  "ObsDiscardAA", "UseDiscardAA", "ObsDiscardAA_pop", "UseDiscardAA_pop",
  "use_discard_aa", "ln_sigmaDAA", "ln_sigmaDAA_pop",
  "AgeObsCorr_catch", "trans_rho_catch", "trans_rho_catch_year", "trans_rho_catch_us",
  "CatchAA_Type", "CatchAA_LikeType", "CatchAA_sigma_form", "ObsCatchAA_SE",
  "AgeObsCorr_catch_pop", "trans_rho_catch_pop", "trans_rho_catch_pop_year",
  "trans_rho_catch_pop_us", "CatchAA_pop_Type", "CatchAA_pop_LikeType",
  "CatchAA_pop_sigma_form", "ObsCatchAA_pop_SE", "AgeObsCorr_discard", "trans_rho_discard",
  "trans_rho_discard_year", "trans_rho_discard_us", "DiscardAA_Type", "DiscardAA_LikeType",
  "DiscardAA_sigma_form", "ObsDiscardAA_SE", "AgeObsCorr_discard_pop", "trans_rho_discard_pop",
  "trans_rho_discard_pop_year", "trans_rho_discard_pop_us", "DiscardAA_pop_Type",
  "DiscardAA_pop_LikeType", "DiscardAA_pop_sigma_form", "ObsDiscardAA_pop_SE",
  "AgeObsCorr_srv_idx", "trans_rho_srv_idx", "trans_rho_srv_idx_year", "trans_rho_srv_idx_us",
  "SrvIdxAA_Type", "SrvIdxAA_LikeType", "SrvIdxAA_sigma_form", "ObsSrvIdxAA_SE",
  "AgeObsCorr_srv_idx_pop", "trans_rho_srv_idx_pop", "trans_rho_srv_idx_pop_year",
  "trans_rho_srv_idx_pop_us", "SrvIdxAA_pop_Type", "SrvIdxAA_pop_LikeType",
  "SrvIdxAA_pop_sigma_form", "ObsSrvIdxAA_pop_SE",
  "PredCatchAA", "PredDiscardAA", "PredSrvIdxAA",
  "sigmaFishIdx_form", "sigmaFishIdx_pop_form", "sigmaSrvIdx_form", "sigmaSrvIdx_pop_form",
  "ln_SrvAge_pop_theta", "ln_SrvAge_pop_theta_agg", "ln_SrvAge_theta", "ln_SrvAge_theta_agg",
  "ln_SrvLen_pop_theta", "ln_SrvLen_pop_theta_agg", "ln_SrvLen_theta", "ln_SrvLen_theta_agg",
  "ln_srvsel_bin_devs", "ln_srvsel_devs", "log_F_x", "log_Fmsy", "log_move_diffusion_pars",
  "logit_dmr_devs", "logit_dmr_mean", "lwr", "M_blocks", "M_prior", "map", "map_ln_F_devs",
  "map_ln_fishsel_bin_devs", "map_ln_fishsel_devs", "map_ln_RecDevs", "map_ln_retsel_bin_devs",
  "map_ln_retsel_devs", "map_ln_srvsel_bin_devs", "map_ln_srvsel_devs", "map_logit_dmr_devs",
  "map_move_devs", "MatAA", "max_bias_ramp_fct", "messages_list", "Model", "move_devs", "move_pars",
  "move_expm_nsub", "move_pe_pars", "move_preference_pars", "move_timing", "move_type", "Movement", "Movement_prior",
  "Mrate", "n_age_dim", "n_ages", "n_conv_tag_cohorts", "n_fish_fleets", "n_pop", "n_pop_in_region",
  "n_proj_yrs_devs", "n_regions", "n_seas", "n_sexes", "n_srv_fleets", "name", "natal_region",
  "NAA_re", "n_est_naa_re", "naa_re_ages", "naa_re_yrs", "naa_re_seas", "naa_sigma_blocks", "ln_NAA", "ln_sigmaNAA", "NAA_pe_pars", "NAA_re_region", "NAA_region_corr_pars", "NAA_re_pop", "NAA_pop_corr_pars", "NAA_re_sex", "NAA_sex_corr_pars", "NAA_re_season", "NAA_season_corr_pars", "NAA_scalar", "sigmaNAA", "naa_rho", "naa_pop_corr", "naa_region_corr", "naa_sex_corr", "naa_season_corr", "naa_eta",
  "natmort", "newton_steps", "obs", "obs_conv_tag_fish_recap", "ObsFishAgeComps",
  "ObsFishAgeComps_discard", "ObsFishAgeComps_discard_pop", "ObsFishAgeComps_pop",
  "ObsFishIdx_pop_SE", "ObsFishIdx_SE", "ObsFishLenComps", "ObsFishLenComps_discard",
  "ObsFishLenComps_discard_pop", "ObsFishLenComps_pop", "ObsSrvAgeComps", "ObsSrvAgeComps_pop",
  "ObsSrvIdx_pop_SE", "ObsSrvIdx_SE", "ObsSrvLenComps", "ObsSrvLenComps_pop", "Par", "Par_Num",
  "peel", "pop", "Pop", "pop_pool", "preference_formula", "prof_val", "q_block", "R0", "r0_prior",
  "rd", "rec_dd", "rec_lag", "sr_penalty", "sr_R0_spec", "sr_pen_yrs", "ln_sigma_sr_pen", "ln_sr_R0", "SR_pred", "rec_level_pen_center", "rec_level_pen_yrs", "rec_model",
  "rec_region_prop", "rec_region_prop_pars", "rec_region_prop_prior", "rec_region_prop_spec",
  "rec_seas_prop", "rec_seas_prop_pars", "rec_seas_prop_prior", "RecDevs_pen_center", "region",
  "Region", "Region_From", "Region_To", "resid", "ret_fixed_sel_pars", "ret_sel",
  "ret_sel_bicubic_binnodes", "ret_sel_bicubic_nselbins", "ret_sel_bicubic_selstyr",
  "ret_sel_bicubic_Wbin", "ret_sel_bicubic_Wyr", "ret_sel_bicubic_yrnodes", "ret_sel_bin_dev_bins",
  "ret_sel_blocks", "ret_sel_input", "ret_sel_model", "ret_sel_pen_wts", "ret_selex_penalty",
  "ret_selex_prior", "ret_selex_type", "retsel_bin_devs_pe_pars", "retsel_bin_devs_rw_init_sigma",
  "retsel_devs_min_shared_bins", "retsel_pe_pars", "retsel_pe_wt", "retsel_rw_init_sigma", "rho",
  "Obs", "Pred",
  "rseas", "ry", "sd", "se", "seas", "Seas", "seasdur", "season", "sex", "Sex", "sex_pool",
  "sex_ratio_f", "sexes", "sexratio_blocks", "sexratio_pars", "sgl_seas_spawning_movement",
  "sigmaR_switch", "SizeAgeTrans", "spawn_seas", "split_index", "SPR_x", "SR_ref_yr",
  "srv_fixed_sel_pars", "srv_idx_ages", "srv_idx_type", "srv_q_blocks", "srv_q_coeff", "srv_q_cov",
  "srv_q_prior", "srv_q_type", "srv_sel_bicubic_binnodes", "srv_sel_bicubic_nselbins",
  "srv_sel_bicubic_selstyr", "srv_sel_bicubic_Wbin", "srv_sel_bicubic_Wyr",
  "srv_sel_bicubic_yrnodes", "srv_sel_bin_dev_bins", "srv_sel_blocks",
  "R0_blocks", "R0_ref_block", "R0_yr", "ln_R0_mat",
  "srv_sel_input",
  "srv_sel_model", "srv_sel_pen_wts", "srv_selex_penalty", "srv_selex_prior", "srv_selex_type",
  "SrvAge_corr_pars", "SrvAge_corr_pars_agg", "SrvAge_pop_corr_pars", "SrvAge_pop_corr_pars_agg",
  "Srv_caal_bins", "SrvAgeComps_bins", "SrvAgeComps_LikeType", "SrvAgeComps_pop_bins",
  "SrvAgeComps_pop_LikeType", "SrvAgeComps_pop_Type",
  "SrvAgeComps_Type", "SrvIdx_Cov", "SrvIdx_LikeType", "SrvLen_corr_pars", "SrvLen_corr_pars_agg",
  "SrvLen_pop_corr_pars", "SrvLen_pop_corr_pars_agg", "SrvLenComps_bins", "SrvLenComps_LikeType",
  "SrvLenComps_pop_bins", "SrvLenComps_pop_LikeType", "SrvLenComps_pop_Type", "SrvLenComps_Type",
  "srvsel_bin_devs_pe_pars",
  "srvsel_bin_devs_rw_init_sigma", "srvsel_devs_min_shared_bins", "srvsel_pe_pars", "srvsel_pe_wt",
  "srvsel_rw_init_sigma", "steepness_h", "stray_rate", "stray_rate_blocks", "stray_rate_pars",
  "stray_rate_prior", "t_fish", "t_spawn", "t_srv", "tc", "terminal", "to", "tr", "tseas", "ty",
  "type", "Type", "uci", "upr", "use_conv_fish_tagging", "use_conv_tag_fishrep_prior",
  "Use_dmr_pen", "Use_F_pen", "Use_fish_q_prior", "Use_fish_selex_penalty", "Use_fish_selex_prior",
  "use_fixed_fish_sel", "use_fixed_movement", "use_fixed_natmort", "use_fixed_rec_seas_prop",
  "use_fixed_ret_sel", "use_fixed_srv_sel", "use_fixed_stray_rate", "Use_h_prior", "Use_M_prior",
  "Use_Movement_Prior", "use_r0_prior", "Use_rec_level_pen", "use_rec_region_prop_prior",
  "use_rec_seas_prop_prior", "Use_ret_selex_penalty", "Use_ret_selex_prior", "use_rinit",
  "Use_srv_q_prior", "Use_srv_selex_penalty", "Use_srv_selex_prior", "use_stray_rate_prior",
  "UseCatch", "UseCatch_pop", "UseDiscard", "UseDiscard_pop", "UseFishAgeComps",
  "UseFishAgeComps_discard", "UseFishAgeComps_discard_pop", "UseFishAgeComps_pop", "UseFishIdx",
  "UseFishIdx_pop", "UseFishLenComps", "UseFishLenComps_discard", "UseFishLenComps_discard_pop",
  "UseFishLenComps_pop", "UseSrvAgeComps", "UseSrvAgeComps_pop", "UseSrvIdx", "UseSrvIdx_pop",
  "UseSrvLenComps", "UseSrvLenComps_pop", "Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7",
  "WAA", "WAA_fish", "WAA_srv", "Wt_Catch", "Wt_Catch_pop", "Wt_D", "Wt_Discard", "Wt_Discard_pop",
  "Wt_F", "Wt_FishAgeComps", "Wt_FishAgeComps_discard", "Wt_FishAgeComps_discard_pop",
  "Wt_FishAgeComps_pop", "Wt_FishIdx", "Wt_FishIdx_pop", "Wt_FishLenComps",
  "Wt_FishLenComps_discard", "Wt_FishLenComps_discard_pop", "Wt_FishLenComps_pop", "Wt_Init_Rec",
  "Wt_Rec", "Wt_SrvAgeComps", "Wt_SrvAgeComps_pop", "Wt_SrvIdx", "Wt_SrvIdx_pop", "Wt_SrvLenComps",
  "Wt_SrvLenComps_pop", "Wt_Tagging", "year", "Year", "years", "years_est"
))
